   version: '3'
   
   services:
     clair:
       image: quay.io/coreos/clair:v4.2.1
       ports:
         - "6060:6060"
       restart: always
       depends_on:
         - postgres
       environment:
         - CLAIR_DATABASE=postgres://username:password@postgres:5432/clair?sslmode=disable
         - CLAIR_UPDATER_ENABLED=true
         - CLAIR_NOTIFIERS_ENABLED=true
         - CLAIR_NOTIFIERS_ENDPOINT=http://clair-notifier:6061/notify
         - CLAIR_API_MAXCONN=1024
   
     postgres:
       image: postgres:12
       environment:
         - POSTGRES_USER=username
         - POSTGRES_PASSWORD=password
       volumes:
         - /var/lib/postgresql/data
